# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Registry Browser paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ docker_registry_browser_uid }}"
    group: "{{ docker_registry_browser_gid }}"
  with_items:
    - "{{ docker_registry_browser_base_path }}"

- name: Ensure Registry Browser support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ docker_registry_browser_base_path }}/{{ item }}"
    owner: "{{ docker_registry_browser_uid }}"
    group: "{{ docker_registry_browser_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure Registry Browser container image is pulled
  community.docker.docker_image:
    name: "{{ docker_registry_browser_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ docker_registry_browser_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else docker_registry_browser_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Registry Browser container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ docker_registry_browser_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Registry Browser systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/registry-browser.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ docker_registry_browser_identifier }}.service"
    mode: 0640
