# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: docker_registry_browser_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: docker_registry_browser_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prepare_basic_auth.yml"

    - when: docker_registry_browser_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-docker-registry-browser
    - install-all
    - install-docker-registry-browser

- block:
    - when: not docker_registry_browser_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-docker-registry-browser
