# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Docker Registry Browser installation tasks
  when: docker_registry_browser_enabled | bool
  tags:
    - setup-all
    - setup-docker-registry-browser
    - install-all
    - install-docker-registry-browser
  block:
    - name: Validate Docker Registry Browser configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Prepare HTTP Basic authentication for Docker Registry Browser
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prepare_basic_auth.yml"
    - name: Install Docker Registry Browser
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Docker Registry Browser uninstallation tasks
  when: not docker_registry_browser_enabled | bool
  tags:
    - setup-all
    - setup-docker-registry-browser
  block:
    - name: Uninstall Docker Registry Browser
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
