# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "docker_registry_browser_systemd_required_systemd_services_list", "new": "docker_registry_browser_systemd_required_services_list" }
    - "old": "docker_registry_browser_container_additional_environment_variables"
      "new": "docker_registry_browser_environment_variables_additional_variables"

- name: Fail if required Container Registry settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - docker_registry_browser_hostname
    - docker_registry_browser_path_prefix
    - docker_registry_browser_uid
    - docker_registry_browser_gid
    - docker_registry_browser_docker_registry_url
    - docker_registry_browser_secret_key_base

- name: Fail if required Container Registry + Traefik integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `docker_registry_browser_container_labels_traefik_enabled`
  when: "docker_registry_browser_container_labels_traefik_enabled | bool and vars[item] == ''"
  with_items:
    - docker_registry_browser_container_labels_traefik_docker_network
